// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolaroidPostsApi.Models;

namespace PolaroidPostsApi.Migrations
{
    [DbContext(typeof(PolaroidPostsApiContext))]
    [Migration("20181120071130_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PolaroidPostsApi.Models.PostItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarURL");

                    b.Property<string>("Caption");

                    b.Property<string>("Email");

                    b.Property<string>("ImageURL");

                    b.Property<int>("Likes");

                    b.Property<string>("Uploaded");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("PostItem");
                });
#pragma warning restore 612, 618
        }
    }
}
