// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolaroidAPI.Models;

namespace PolaroidAPI.Migrations
{
    [DbContext(typeof(PolaroidAPIContext))]
    [Migration("20181121144016_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PolaroidAPI.Models.PostItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<string>("ImageURL");

                    b.Property<int>("Likes");

                    b.Property<DateTime>("Uploaded");

                    b.Property<int>("UserID");

                    b.HasKey("Id");

                    b.ToTable("PostItem");
                });

            modelBuilder.Entity("PolaroidAPI.Models.Relationships", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Follows");

                    b.Property<int>("Person");

                    b.HasKey("Id");

                    b.ToTable("Relationships");
                });

            modelBuilder.Entity("PolaroidAPI.Models.UserItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvatarURL");

                    b.Property<string>("Bio");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("UserItem");
                });
#pragma warning restore 612, 618
        }
    }
}
